// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/ElegantMinimal.tsx": () => import("../components/mockups/login-variants/ElegantMinimal.tsx"),
  "./components/mockups/login-variants/PremiumDark.tsx": () => import("../components/mockups/login-variants/PremiumDark.tsx"),
  "./components/mockups/login-variants/SaudiModern.tsx": () => import("../components/mockups/login-variants/SaudiModern.tsx")
};
